ORG 0000H
LJMP MAIN
ORG 0003H ; External Interrupt INT0 is used
LJMP THROW
ORG 0030H
MAIN: MOV P1,#00H
MOV IE,#81H
ACALL LCD_INITIALISE
MOV DPTR, #CODE1
INTRO: CLR A
MOVC A, @A+DPTR
MOV P1,A
ACALL DATAWRT
ACALL DELAY
INC DPTR
JZ NEXT1
SJMP INTRO
NEXT1: NOP
MOV R1,#01H
RANDOM:
CJNE R1,#06H,NEXT
MOV R1,#01H
NEXT: INC R1
SJMP RANDOM
LCD_INITIALISE: MOV A,#38H; the code to initialise the LCD
ACALL COMNWRT
ACALL DELAY
MOV A,#0EH
ACALL COMNWRT
ACALL DELAY
MOV A,#01H
ACALL COMNWRT
ACALL DELAY
MOV A, #06H
ACALL COMNWRT
ACALL DELAY
MOV A,#81H
ACALL COMNWRT
ACALL DELAY
RET
CODE1: DB 'Ready to roll?', 0
ORG 0300H
THROW: CJNE R1,#01H,CHECK2
MOV DPTR, #CODE2
LOOP1: CLR A
MOVC A, @A+DPTR
MOV P1,A
ACALL DATAWRT
ACALL DELAY
INC DPTR
JZ NEXTT1
SJMP LOOP1
NEXTT1:MOV P1,#'1'
ACALL DATAWRT
ACALL DELAY1
MOV A, #01H
ACALL COMNWRT
ACALL DELAY
LJMP EXIT
CHECK2: CJNE R1,#02H, CHECK3
MOV DPTR, #CODE2
LOOP2: CLR A
MOVC A, @A+DPTR
MOV P1,A
ACALL DATAWRT
ACALL DELAY
INC DPTR
JZ NEXT2
SJMP LOOP2
NEXT2: MOV P1,#'2'
ACALL DATAWRT
ACALL DELAY1
MOV A, #01H
ACALL COMNWRT
ACALL DELAY
LJMP EXIT
CHECK3: CJNE R1,#03H, CHECK4
MOV DPTR, #CODE2
LOOP3: CLR A
MOVC A, @A+DPTR
MOV P1,A
ACALL DATAWRT
ACALL DELAY
INC DPTR
JZ NEXT3
LJMP LOOP3
NEXT3: MOV P1,#'3'
ACALL DATAWRT
ACALL DELAY1
MOV A, #01H
ACALL COMNWRT
ACALL DELAY
LJMP EXIT
CHECK4: CJNE R1, #04H, CHECK5
MOV DPTR, #CODE2
LOOP4: CLR A
MOVC A, @A+DPTR
MOV P1,A
ACALL DATAWRT
ACALL DELAY
INC DPTR
JZ NEXT4
LJMP LOOP4
NEXT4: MOV P1, #'4’
ACALL DATAWRT
ACALL DELAY1
MOV A, #01H
ACALL COMNWRT
ACALL DELAY
LJMP EXIT
CHECK5: CJNE R1,#05H, CHECK6
MOV DPTR, #CODE2
LOOP5: CLR A
MOVC A, @A+DPTR
MOV P1,A
ACALL DATAWRT
ACALL DELAY
INC DPTR
JZ NEXT5
LJMP LOOP5
NEXT5: MOV P1, #'5’
ACALL DATAWRT
ACALL DELAY1
MOV A, #01H
ACALL COMNWRT
ACALL DELAY
LJMP EXIT
CHECK6: MOV DPTR, #CODE2
LOOP6: CLR A
MOVC A, @A+DPTR
MOV P1,A
ACALL DATAWRT
ACALL DELAY
INC DPTR
JZ NEXT6
LJMP LOOP6
NEXT6: MOV P1, #'6’
ACALL DATAWRT
ACALL DELAY1
MOV A, #01H
ACALL COMNWRT
ACALL DELAY
EXIT: NOP
RETI
CODE2: DB 'The number is:', 0
;We shall assume P1 is the port connected to the LCD.
;P2.0 is Reset, P2.1 is R/W, P2.2 is Enable
COMNWRT: MOV P1, A
CLR P2.0
CLR P2.1
SETB P2.2
ACALL DELAY
CLR P2.2
RET
DATAWRT: SETB P2.0
CLR P2.1
SETB P2.2
ACALL DELAY
CLR P2.2
RET
DELAY: MOV R3, #50
HERE1: MOV R4, #255
HERE2: DJNZ R4, HERE2
DJNZ R3, HERE1
RET
DELAY1:MOV R0,#100
MOV TMOD, #01H
AGAIN: MOV TL0, #00H
MOV TH0, #00H
SETB TR0
HERE: JNB TF0, HERE
CLR TR0
CLR TF0
DJNZ R0, AGAIN
RET
END